package de.wirvsvirus.hack.model;

public enum StockAvatar {
    DANI, DIMI, GUDRUN, LISA, MIRIAM, STEFAN,
    DUPERMAN, CYBERPUNK, GUY_FAWKES, GIRL_HUGE_HAIR, AGED_HIPSTER, ANXIOUS_ROBOT, PANDA_HEART, CAT_HEART
}