package de.wirvsvirus.hack.model;

public enum StockAvatar {
  DANI, DIMI, GUDRUN, LISA, MIRIAM, STEFAN,
  DUPERMAN, CYBERPUNK, GUY_FAWKES, GIRL_HUGE_HAIR, AGED_HIPSTER, ANXIOUS_ROBOT, PANDA_HEART, CAT_HEART,
  BUILDER_HELMET, CORONAMASKED_MAN, COUCH_POTATO, GIRL_GOLDEN_GLASSES, NEAT_WOMAN, RAPPER_KID, YOUNG_TRUMP,
  HIPSTER_SUMO_HAIR, SKELETON_DEATH, PIG_SHAMROCK, LEPRECHAUN, ICEBEAR, GIRL_HAPPY_WITH_HAIR, MAN_SWEATING, GIRL_YELLOW,
  CUTE_REDHAIR
}